version: "3.7"

services:
  trading-api:
    image: ghcr.io/pokedex-gamba/trading-api:latest
    ports:
      - "8891:80"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-trading:3306/pokemon_trading
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - INVENTORY_API_URL=http://host.docker.internal:8889
    depends_on:
      - db-trading
    volumes:
      - ./decoding_key:/decoding_key
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db-trading:
    image: mysql:8.0
    build: ./database
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: pokemon_trading
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
